# Lecture 13

# Working with tables in pandas

## Week 5 Monday

## Miles Chen, PhD

## From arrays to tables

A NumPy array has one `dtype`. A pandas **DataFrame** is a two-dimensional table
with row and column labels. Its columns can have different dtypes.

Selecting one column gives a **Series**: a one-dimensional object with labels
and a dtype. A Series can use NumPy storage or other array types; a DataFrame is
not simply a single NumPy matrix.

Use the conventional import:

In [1]:
import pandas as pd

pd.__version__

'3.0.1'

## 1. Read a table

`pd.read_csv()` reads a comma-separated file into a DataFrame.
Here, one row is one passenger record. These 891 records are not a complete
list of everyone aboard the Titanic.

Run this notebook with `live_demos` as the working directory. `..` means the
parent folder, where the course's `data` directory is located.

In [2]:
titanic = pd.read_csv("../data/titanic.csv")
titanic.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### A few variables we will use

| Column | Meaning |
|---|---|
| `passengerid` | Passenger identifier in this dataset |
| `survived` | Recorded survival: 0 = no, 1 = yes |
| `pclass` | Ticket class: 1st, 2nd, or 3rd |
| `name`, `sex`, `age` | Recorded passenger information; age is in years |
| `sibsp` | Number of siblings/spouses aboard |
| `parch` | Number of parents/children aboard |
| `fare` | Recorded passenger fare |
| `embarked` | Embarkation code: C = Cherbourg, Q = Queenstown, S = Southampton |

An identifier or category can be stored as an integer. Its dtype alone does not
tell us whether taking an average would be meaningful.

## 2. Inspect before analyzing

`head()` shows the first five rows by default. You can request a different number.
`shape` is an attribute containing `(number_of_rows, number_of_columns)`.

In [3]:
titanic.head(3)

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [4]:
titanic.shape

(891, 12)

In [5]:
titanic.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [6]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

### Row labels and data values

The displayed numbers on the far left are the **index**, or row labels. This file
gets the default labels 0, 1, 2, ... . The `passengerid` column contains data values;
it is separate from the index.

We can leave the default index in place for our analysis. Filtering or sorting
usually keeps the existing row labels, so they need not remain consecutive or
match a row's current position.

In [7]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   name         891 non-null    str
 4   sex          891 non-null    str
 5   age          714 non-null    float64
 6   sibsp        891 non-null    int64
 7   parch        891 non-null    int64
 8   ticket       891 non-null    str
 9   fare         891 non-null    float64
 10  cabin        204 non-null    str
 11  embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [8]:
titanic.dtypes

passengerid      int64
survived         int64
pclass           int64
name               str
sex                str
age            float64
sibsp            int64
parch            int64
ticket             str
fare           float64
cabin              str
embarked           str
dtype: object

### What do these outputs tell us?

- `info()` reports each column's dtype and number of **nonmissing** values.
  There are 891 passenger records, but only 714 recorded ages.
- In pandas 3, text commonly has the dedicated `str` dtype. Older examples may
  show `object`; `object` can also hold a mixture of Python objects.
- Missing values have different representations depending on dtype, including
  `NaN`, `pd.NA`, and `NaT`. We will study how to detect and handle them in lecture 14.

Which columns are identifiers, categories, and measurements?
What does the missing-age count prevent us from assuming?

## 3. Select columns

Use square brackets with a **single column name** to get a Series.
Column names are strings, so put them in quotes.

In [9]:
ages = titanic["age"]
ages.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [10]:
type(ages), ages.shape

(pandas.Series, (891,))

### Select a list of column names

The inner brackets create a Python list. The outer brackets select those columns
from the DataFrame, in the order you provide.

In [11]:
titanic[["name", "age", "fare"]].head()

                                                name   age     fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [12]:
# Even a list containing just one name returns a DataFrame.
age_table = titanic[["age"]]
age_table.head()

    age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

### Predict the result

What are the type and shape of each expression?

1. `titanic["age"]`
2. `titanic[["age"]]`
3. `titanic[["age", "fare"]]`

You may see `titanic.age` in other code. We will use brackets consistently:
they also work for names with spaces and names that conflict with DataFrame methods.

In [13]:
print(type(titanic["age"]), titanic["age"].shape)
print(type(titanic[["age"]]), titanic[["age"]].shape)
print(type(titanic[["age", "fare"]]), titanic[["age", "fare"]].shape)

<class 'pandas.Series'> (891,)
<class 'pandas.DataFrame'> (891, 1)
<class 'pandas.DataFrame'> (891, 2)

## 4. Labels and positions: a small Avengers table

Here is one useful way to construct a DataFrame: give a dictionary whose keys
are column names and whose values are equal-length lists.

We will use character names as row labels to make the distinction between labels
and positions visible. The ages are illustrative values for this fictional example.

In [14]:
avengers = pd.DataFrame(
    {
        "actor": ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson", "Chris Hemsworth"],
        "hero name": ["Iron Man", "Captain America", "Black Widow", "Thor"],
        "age": [42, 104, 28, 1493],
    },
    index=["Tony Stark", "Steve Rogers", "Natasha Romanoff", "Thor"],
)
avengers

                               actor        hero name   age
Tony Stark         Robert Downey Jr.         Iron Man    42
Steve Rogers             Chris Evans  Captain America   104
Natasha Romanoff  Scarlett Johansson      Black Widow    28
Thor                 Chris Hemsworth             Thor  1493

### `.loc[rows, columns]` selects by label

Supply a row label and a column label to get a value. A colon `:` means all labels
along that dimension. Lists of both row and column labels keep the result as a DataFrame.

In [15]:
avengers.loc["Thor", "age"]

np.int64(1493)

In [16]:
avengers.loc[["Thor", "Natasha Romanoff"], ["hero name", "age"]]

                    hero name   age
Thor                     Thor  1493
Natasha Romanoff  Black Widow    28

In [17]:
avengers.loc[:, "age"]  # all rows, one column: a Series

Tony Stark            42
Steve Rogers         104
Natasha Romanoff      28
Thor                1493
Name: age, dtype: int64

### `.iloc[rows, columns]` selects by position

Positions start at zero. Positional slices exclude the stop, just as in Python
lists and NumPy arrays.

Use `.loc` when you mean labels; use `.iloc` when you mean positions. For example,
`.loc[1]` would mean the row labeled 1, even if it is not the second row.

In [18]:
avengers.iloc[0]  # first row, returned as a Series

actor        Robert Downey Jr.
hero name             Iron Man
age                         42
Name: Tony Stark, dtype: object

In [19]:
avengers.iloc[:2, :2]  # first two rows and first two columns

                          actor        hero name
Tony Stark    Robert Downey Jr.         Iron Man
Steve Rogers        Chris Evans  Captain America

## 5. Filter rows with a Boolean condition

Back to Titanic: which records are for first-class passengers?

A comparison produces one Boolean value per row. The condition below is a
Series whose index matches the table it came from.

In [20]:
first_class = titanic["pclass"] == 1
first_class.head(10)

0    False
1     True
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
Name: pclass, dtype: bool

In [21]:
titanic.loc[first_class, ["name", "pclass", "fare"]].head()

                                                 name  pclass     fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000
6                             McCarthy, Mr. Timothy J       1  51.8625
11                           Bonnell, Miss. Elizabeth       1  26.5500
23                       Sloper, Mr. William Thompson       1  35.5000

### Put the condition directly inside `.loc`

The general pattern is `df.loc[row_condition, column_names]`.
Build the condition from the same DataFrame you are filtering.

In [22]:
titanic.loc[titanic["pclass"] == 1, ["name", "pclass", "fare"]].head()

                                                 name  pclass     fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000
6                             McCarthy, Mr. Timothy J       1  51.8625
11                           Bonnell, Miss. Elizabeth       1  26.5500
23                       Sloper, Mr. William Thompson       1  35.5000

### Combine conditions

As with NumPy, use `&` for elementwise AND, `|` for elementwise OR, and `~` for NOT.
Put parentheses around each comparison. Python's `and` and `or` do not combine
these Series element by element.

In [23]:
# Female passengers in first class.
titanic.loc[
    (titanic["sex"] == "female") & (titanic["pclass"] == 1),
    ["name", "sex", "pclass", "fare"],
].head()

,name,sex,pclass,fare
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,71.2833
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,53.1000
11,"Bonnell, Miss. Elizabeth",female,1,26.5500
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,1,146.5208
52,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,1,76.7292

In [24]:
# Passengers in either first or second class.
titanic.loc[
    (titanic["pclass"] == 1) | (titanic["pclass"] == 2),
    ["name", "pclass", "fare"],
].head()

                                                 name  pclass     fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000
6                             McCarthy, Mr. Timothy J       1  51.8625
9                 Nasser, Mrs. Nicholas (Adele Achem)       2  30.0708
11                           Bonnell, Miss. Elizabeth       1  26.5500

### Membership: `.isin()`

`isin()` tests membership in a collection of values. It is often clearer than
writing a long sequence of OR conditions.

In [25]:
titanic.loc[
    titanic["pclass"].isin([1, 2]),
    ["name", "pclass", "fare"],
].head()

                                                 name  pclass     fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000
6                             McCarthy, Mr. Timothy J       1  51.8625
9                 Nasser, Mrs. Nicholas (Adele Achem)       2  30.0708
11                           Bonnell, Miss. Elizabeth       1  26.5500

### An age condition uses the recorded ages

The following selects passengers with recorded ages of at least 18.
In this CSV, missing ages are floating-point `NaN`; their comparison to 18 is
`False`, so those rows are excluded.

An excluded passenger is therefore not necessarily a child. We will return
to missingness and its effect on an analysis in lecture 14.

In [26]:
titanic.loc[titanic["age"] >= 18, ["name", "age"]].head()

                                                name   age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

### Your turn: select and filter

Show `name`, `pclass`, and `fare` for third-class passengers whose recorded fare
is below 10.

1. Write the Boolean condition and save it as `low_fare_third_class`.
2. Select the matching rows and the three requested columns.
3. Display the first five results.

In [27]:
# Try your solution here before continuing.

### One solution

The condition chooses rows. The list of names chooses columns. `head()` controls
how many results we display; it is separate from the fare condition.

In [28]:
low_fare_third_class = (titanic["pclass"] == 3) & (titanic["fare"] < 10)
low_fare_passengers = titanic.loc[
    low_fare_third_class, ["name", "pclass", "fare"]
]
low_fare_passengers.head()

                              name  pclass    fare
0          Braund, Mr. Owen Harris       3  7.2500
2           Heikkinen, Miss. Laina       3  7.9250
4         Allen, Mr. William Henry       3  8.0500
5                 Moran, Mr. James       3  8.4583
12  Saundercock, Mr. William Henry       3  8.0500

## 6. Create variables with column operations

Arithmetic on columns works element by element. We can save the result as a new
column using `df["new_name"] = expression`.

`sibsp + parch` counts recorded siblings/spouses and parents/children aboard.
Call this **relatives_aboard**; it does not include the passenger.

In [29]:
titanic["relatives_aboard"] = titanic["sibsp"] + titanic["parch"]
titanic[["name", "sibsp", "parch", "relatives_aboard"]].head()

,name,sibsp,parch,relatives_aboard
0,"Braund, Mr. Owen Harris",1,0,1
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,1
2,"Heikkinen, Miss. Laina",0,0,0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,1
4,"Allen, Mr. William Henry",0,0,0

In [30]:
titanic["no_recorded_relatives"] = titanic["relatives_aboard"] == 0
titanic[["name", "relatives_aboard", "no_recorded_relatives"]].head()

,name,relatives_aboard,no_recorded_relatives
0,"Braund, Mr. Owen Harris",1,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,False
2,"Heikkinen, Miss. Laina",0,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,False
4,"Allen, Mr. William Henry",0,True

### What did we just change?

We added columns while keeping the same passenger rows. These expressions use
vectorized column operations; no loop over passengers is needed.

**Interpretation:** `no_recorded_relatives` means zero recorded relatives in the
`sibsp` and `parch` categories. It does not establish that a passenger had no
friends or other companions aboard.

Both source columns are complete in this file. If they contained missing values,
we would need to consider what an unknown count means before creating the flag.

In [31]:
titanic.shape

(891, 14)

### Modify the intended table directly

Use a single `.loc[rows, columns] = value` operation for an update to selected
cells. We will change an illustrative value in the Avengers table.

Avoid chained assignment such as `df["column"][condition] = value`. In pandas 3,
that does not update the original DataFrame. A selected subset behaves independently
when modified; the optional examples show this rule in action.

In [32]:
avengers.loc["Thor", "age"] = 1500
avengers.loc[["Thor"], ["hero name", "age"]]

     hero name   age
Thor      Thor  1500

## 7. Sort whole rows

`sort_values()` orders the table using one or more columns. The values within
each passenger record stay together.

Ascending order is the default. Use `ascending=False` for descending order.
Sorting returns a result; assign it to a variable if you want to keep it.

In [33]:
titanic.sort_values("fare").loc[:, ["name", "pclass", "fare"]].head()

                                 name  pclass  fare
815                  Fry, Mr. Richard       1   0.0
806            Andrews, Mr. Thomas Jr       1   0.0
413    Cunningham, Mr. Alfred Fleming       2   0.0
481  Frost, Mr. Anthony Wood "Archie"       2   0.0
302   Johnson, Mr. William Cahoone Jr       3   0.0

In [34]:
highest_fares = titanic.sort_values(
    ["fare", "passengerid"], ascending=[False, True]
)
highest_fares[["passengerid", "name", "pclass", "fare"]].head()

     passengerid                                name  pclass      fare
258          259                    Ward, Miss. Anna       1  512.3292
679          680  Cardeza, Mr. Thomas Drake Martinez       1  512.3292
737          738              Lesurer, Mr. Gustave J       1  512.3292
27            28      Fortune, Mr. Charles Alexander       1  263.0000
88            89          Fortune, Miss. Mabel Helen       1  263.0000

### Sorting by more than one column

Above, fare is the main sort key. Passenger ID breaks fare ties in increasing
order, making the displayed order predictable.

The original `titanic` still has its original row order. `highest_fares` has the
same rows in a new order, with their existing index labels.

In [35]:
titanic[["passengerid", "fare"]].head()

   passengerid     fare
0            1   7.2500
1            2  71.2833
2            3   7.9250
3            4  53.1000
4            5   8.0500

### Labels stay with rows; positions can change

Predict: after sorting Avengers from youngest to oldest, will `.loc["Thor"]`
still select Thor? Who will `.iloc[0]` select?

In [36]:
avengers_by_age = avengers.sort_values("age")
avengers_by_age[["hero name", "age"]]

                        hero name   age
Natasha Romanoff      Black Widow    28
Tony Stark               Iron Man    42
Steve Rogers      Captain America   104
Thor                         Thor  1500

In [37]:
avengers_by_age.loc["Thor", "hero name"], avengers_by_age.iloc[0]["hero name"]

('Thor', 'Black Widow')

## 8. Put the operations together

**Question:** Among third-class passengers who survived and had no recorded
relatives aboard, which ten records have the highest fares?

1. Filter for all three conditions.
2. Keep `passengerid`, `name`, `sex`, `age`, `fare`, and `relatives_aboard`.
3. Sort by descending fare, then ascending passenger ID to break ties.
4. Display the first ten rows.

Before coding, describe the steps using the familiar ideas **filter**, **select**,
**mutate**, and **arrange**. Which step have we already completed?

In [38]:
# Build your result here. The derived columns already exist in titanic.

### One solution: name the intermediate result

The Boolean column can be used directly as a condition; it already contains
`True` or `False` values.

In [39]:
selected_passengers = titanic.loc[
    (titanic["pclass"] == 3)
    & (titanic["survived"] == 1)
    & titanic["no_recorded_relatives"],
    ["passengerid", "name", "sex", "age", "fare", "relatives_aboard"],
]

fare_order = selected_passengers.sort_values(
    ["fare", "passengerid"], ascending=[False, True]
)
fare_order.head(10)

,passengerid,name,sex,age,fare,relatives_aboard
74,75,"Bing, Mr. Lee",male,32.0,56.4958,0
509,510,"Lang, Mr. Fang",male,26.0,56.4958,0
643,644,"Foo, Mr. Choong",male,NaN,56.4958,0
692,693,"Lam, Mr. Ali",male,NaN,56.4958,0
838,839,"Chip, Mr. Chang",male,32.0,56.4958,0
207,208,"Albimona, Mr. Nassef Cassem",male,26.0,18.7875,0
79,80,"Dowdell, Miss. Elizabeth",female,30.0,12.4750,0
777,778,"Emanuel, Miss. Virginia Ethel",female,5.0,12.4750,0
677,678,"Turja, Miss. Anna Sofia",female,18.0,9.8417,0
483,484,"Turkula, Mrs. (Hedwig)",female,63.0,9.5875,0

### Read the result carefully

- How many records met the conditions, before taking the first ten?
- Why are some displayed ages missing, even though our code ran successfully?
- Did selecting columns change the number of rows? Did sorting?
- Could this filtered list establish whether having relatives affected survival?

We did not filter on age, so unknown ages can remain. This is a selected list of
survivors, not a comparison of survival rates. Lecture 14 will build comparisons
with explicit group sizes and denominators.

In [40]:
selected_passengers.shape

(69, 6)

## The verbs you already know

| Task | R/dplyr idea | pandas pattern used today |
|---|---|---|
| Select columns | `select()` | `df[["col1", "col2"]]` |
| Filter rows | `filter()` | `df.loc[condition, columns]` |
| Create a variable | `mutate()` | `df["new"] = expression` |
| Order rows | `arrange()` | `df.sort_values(...)` |

These are conceptual translations, not identical function names. In particular,
pandas' method named `.filter()` selects labels; it is not dplyr's row-condition filter.

Next: missingness, duplicate records, and grouped summaries. Later we will use
these same operations in Polars and prepare tables for visualization.

### chain operations

Methods such as `sort_values()` and `head()` return objects that support the next
operation. Parentheses let us write the steps on separate lines. This reproduces
the cumulative exercise without naming its intermediate tables.

In [41]:
(
    titanic.loc[
        (titanic["pclass"] == 3)
        & (titanic["survived"] == 1)
        & titanic["no_recorded_relatives"],
        ["passengerid", "name", "sex", "age", "fare", "relatives_aboard"],
    ]
    .sort_values(["fare", "passengerid"], ascending=[False, True])
    .head(10)
)

,passengerid,name,sex,age,fare,relatives_aboard
74,75,"Bing, Mr. Lee",male,32.0,56.4958,0
509,510,"Lang, Mr. Fang",male,26.0,56.4958,0
643,644,"Foo, Mr. Choong",male,NaN,56.4958,0
692,693,"Lam, Mr. Ali",male,NaN,56.4958,0
838,839,"Chip, Mr. Chang",male,32.0,56.4958,0
207,208,"Albimona, Mr. Nassef Cassem",male,26.0,18.7875,0
79,80,"Dowdell, Miss. Elizabeth",female,30.0,12.4750,0
777,778,"Emanuel, Miss. Virginia Ethel",female,5.0,12.4750,0
677,678,"Turja, Miss. Anna Sofia",female,18.0,9.8417,0
483,484,"Turkula, Mrs. (Hedwig)",female,63.0,9.5875,0

### filter text values

The `.str` accessor applies string operations to a Series. Here, `regex=False`
asks for a literal substring, and `na=False` treats missing names as nonmatches.

In [42]:
titanic.loc[
    titanic["name"].str.contains("Williams", regex=False, na=False),
    ["name", "age", "pclass"],
]

                                       name   age  pclass
17             Williams, Mr. Charles Eugene   NaN       2
155             Williams, Mr. Charles Duane  51.0       1
304       Williams, Mr. Howard Hugh "Harry"   NaN       3
351  Williams-Lambert, Mr. Fletcher Fellows   NaN       1
607             Daniel, Mr. Robert Williams  27.0       1
735                    Williams, Mr. Leslie  28.5       3

### label slices versus position slices

With these ordered, unique row labels, a `.loc` label slice includes both
endpoints. An `.iloc` position slice excludes the stop.

In [43]:
avengers.loc["Tony Stark":"Natasha Romanoff", ["hero name", "age"]]

                        hero name  age
Tony Stark               Iron Man   42
Steve Rogers      Captain America  104
Natasha Romanoff      Black Widow   28

In [44]:
avengers.iloc[0:2, :]  # only the first two rows

                          actor        hero name  age
Tony Stark    Robert Downey Jr.         Iron Man   42
Steve Rogers        Chris Evans  Captain America  104

### Series align by label

Constructing a Series from a dictionary uses its keys as labels. When a Series
is assigned to a DataFrame column, pandas matches row labels, rather than merely
using the Series' current order.

This is one reason to keep track of labels when creating columns from another table.

In [45]:
# The dictionary order deliberately differs from the Avengers row order.
appearances = pd.Series({
    "Thor": "Thor",
    "Natasha Romanoff": "Iron Man 2",
    "Steve Rogers": "Captain America: The First Avenger",
    "Tony Stark": "Iron Man",
})

avengers_with_films = avengers.copy()
avengers_with_films["first_MCU_film"] = appearances
avengers_with_films[["hero name", "first_MCU_film"]]

                        hero name                      first_MCU_film
Tony Stark               Iron Man                            Iron Man
Steve Rogers      Captain America  Captain America: The First Avenger
Natasha Romanoff      Black Widow                          Iron Man 2
Thor                         Thor                                Thor

### selecting a subset in pandas 3

A selected Series behaves independently when you modify it. To change the
DataFrame, assign directly to that DataFrame instead.

This differs from the shared-data behavior of the NumPy basic slices studied in
lecture 11. Simply writing `other = avengers` would still give two names for the
same object; selecting a column is a different operation.

In [46]:
age_subset = avengers["age"]
age_subset.loc["Thor"] = 1600

print("Selected Series:", age_subset.loc["Thor"])
print("Original DataFrame:", avengers.loc["Thor", "age"])

Selected Series: 1600
Original DataFrame: 1500

### converting a Series to a NumPy array

`to_numpy()` returns an ndarray without the Series' index labels. Its dtype may
differ from the Series' dtype. A mixed row like the one below produces an ordinary
`object` array holding Python objects; it is not a structured array with named fields.

In [47]:
thor_values = avengers.loc["Thor"].to_numpy()
print(thor_values)
print(type(thor_values), thor_values.dtype)

['Chris Hemsworth' 'Thor' np.int64(1500)]
<class 'numpy.ndarray'> object

### a quick numeric overview

`describe()` summarizes numeric columns by default. Selecting measurements first
keeps identifiers and category codes out of the summary. `count` is the number of
nonmissing observations for each selected column.

These summaries describe the recorded values; they do not resolve missingness.

In [48]:
titanic[["age", "fare"]].describe()

              age        fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

### References

- [pandas: reading and writing tabular data](https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html)
- [pandas: selecting a subset](https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html)
- [pandas: creating columns](https://pandas.pydata.org/docs/getting_started/intro_tutorials/05_add_columns.html)
- [Indexing and selecting data](https://pandas.pydata.org/pandas-docs/version/3.0/user_guide/indexing.html)
- [Missing data](https://pandas.pydata.org/pandas-docs/version/3.0/user_guide/missing_data.html)
- [pandas 3 string dtype](https://pandas.pydata.org/pandas-docs/version/3.0/user_guide/migration-3-strings.html)
- [Copy-on-Write](https://pandas.pydata.org/pandas-docs/version/3.0/user_guide/copy_on_write.html)